process.env.KORSHI_NO_LISTEN='1';
const { app } = await import('./dist/index.js');
const srv = app.listen(0); await new Promise(r=>srv.once('listening',r));
const base='http://127.0.0.1:'+srv.address().port; let pass=0,fail=0;
const ok=(c,m)=>{c?pass++:(fail++,console.log('FAIL:',m))}; const J=r=>r.json();
let r=await fetch(base+'/api/auth/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'admin@korshi.kz',password:'admin123'})});
let a=await J(r); ok(r.status===200&&a.token,'admin login'); const AT=a.token;
ok((await fetch(base+'/api/auth/admin/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'admin@korshi.kz',password:'x'})})).status===401,'admin bad pw');
ok((await fetch(base+'/api/admin/stats')).status===401,'stats needs auth');
let s=await J(await fetch(base+'/api/admin/stats',{headers:{authorization:'Bearer '+AT}}));
ok(s.residents===3&&s.reportsTotal===3,'stats counts');
r=await fetch(base+'/api/auth/resident/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone:'+7 777 123 45 67',secret:'ab12-48'})});
let rl=await J(r); ok(r.status===200&&rl.token,'resident login fuzzy'); const RT=rl.token; const RH={authorization:'Bearer '+RT};
ok((await fetch(base+'/api/auth/resident/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone:'+77771234567',secret:'no'})})).status===401,'resident bad code');
let home=await J(await fetch(base+'/api/home',{headers:RH})); ok(home.announcement.title&&home.poll.question&&home.contacts.length&&home.partner.phone,'home');
let upd=await J(await fetch(base+'/api/updates',{headers:RH})); ok(upd.pinned.title&&upd.latest.length,'updates');
let cts=await J(await fetch(base+'/api/contacts',{headers:RH})); ok(cts.important.length===4&&cts.services.length===4&&cts.partners.length===3,'contacts');
let reps=await J(await fetch(base+'/api/reports',{headers:RH})); ok(reps.length===3,'reports list');
let det=await J(await fetch(base+'/api/reports/r1',{headers:RH})); ok(det.description&&det.detailSteps.length&&det.chairmanUpdates.length,'detail');
r=await fetch(base+'/api/reports',{method:'POST',headers:{...RH,'content-type':'application/json'},body:JSON.stringify({category:'water',description:'тест',location:'X'})});
ok(r.status===201,'create report'); ok((await J(await fetch(base+'/api/reports',{headers:RH}))).length===4,'report in list');
let polls=await J(await fetch(base+'/api/polls',{headers:RH}));
ok(polls.active.id&&polls.active.options[0].id,'poll ids present');
ok((await fetch(base+'/api/polls/'+polls.active.id+'/vote',{method:'POST',headers:{...RH,'content-type':'application/json'},body:JSON.stringify({optionId:polls.active.options[0].id})})).status===200,'vote');
ok((await J(await fetch(base+'/api/polls',{headers:RH}))).active.voted===true,'voted');
r=await fetch(base+'/api/admin/announcements',{method:'POST',headers:{authorization:'Bearer '+AT,'content-type':'application/json'},body:JSON.stringify({type:'event',title:'T',message:'m'})});
let na=await J(r); ok(r.status===201,'create ann'); ok((await fetch(base+'/api/admin/announcements/'+na.id,{method:'DELETE',headers:{authorization:'Bearer '+AT}})).status===200,'del ann');
r=await fetch(base+'/api/admin/polls',{method:'POST',headers:{authorization:'Bearer '+AT,'content-type':'application/json'},body:JSON.stringify({question:'Q',options:['a','b'],durationDays:7})});
let np=await J(r); ok(r.status===201,'create poll'); ok((await fetch(base+'/api/admin/polls/'+np.id,{method:'DELETE',headers:{authorization:'Bearer '+AT}})).status===200,'del poll');
r=await fetch(base+'/api/admin/residents/invite',{method:'POST',headers:{authorization:'Bearer '+AT,'content-type':'application/json'},body:JSON.stringify({phone:'+77001112222',address:'ул. Новая, 1'})});
let inv=await J(r); ok(/^[A-Z0-9]{4}-[A-Z0-9]{2}$/.test(inv.activationCode),'invite code');
ok((await fetch(base+'/api/auth/resident/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone:'+77001112222',secret:inv.activationCode})})).status===200,'invited logs in');
ok((await fetch(base+'/api/auth/resident/password',{method:'POST',headers:{...RH,'content-type':'application/json'},body:JSON.stringify({password:'mypass1'})})).status===200,'set pw');
ok((await fetch(base+'/api/auth/resident/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone:'+77771234567',secret:'mypass1'})})).status===200,'login pw');
ok((await fetch(base+'/api/auth/resident/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phone:'+77771234567',secret:'AB12-48'})})).status===200,'code still works');
r=await fetch(base+'/api/admin/reports/r2',{method:'PATCH',headers:{authorization:'Bearer '+AT,'content-type':'application/json'},body:JSON.stringify({status:'inProgress',contractor:'X'})});
let pr=await J(r); ok(pr.status==='inProgress'&&pr.contractor==='X','patch report');
let ur=await J(await fetch(base+'/api/admin/reports/r2/update',{method:'POST',headers:{authorization:'Bearer '+AT,'content-type':'application/json'},body:JSON.stringify({body:'upd'})}));
ok(ur.chairmanUpdates.at(-1).body==='upd','add update');
let adminReps=await J(await fetch(base+'/api/admin/reports',{headers:{authorization:'Bearer '+AT}})); ok(adminReps.length===4,'admin sees all reports');
srv.close(); console.log(`\nRESULT: ${pass} passed, ${fail} failed`); process.exit(fail?1:0);
